# Generated by Django 2.2.9 on 2020-01-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TEST",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test", models.BigIntegerField()),
                ("test1", models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
