# Generated by Django 2.2.9 on 2020-01-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customtext_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.GenericIPAddressField(protocol='IPv4')),
            ],
        ),
    ]
